"""Checked-in exhaustive kana romanization fixtures."""

from std.collections import List


struct KanaFixture(Copyable):
    var kana: String
    var romaji: String

    def __init__(out self, kana: StringSlice, romaji: StringSlice):
        self.kana = String(kana)
        self.romaji = String(romaji)


struct KanaVoicingFixture(Copyable):
    var base: String
    var mark: String
    var composed: String
    var romaji: String

    def __init__(
        out self,
        base: StringSlice,
        mark: StringSlice,
        composed: StringSlice,
        romaji: StringSlice,
    ):
        self.base = String(base)
        self.mark = String(mark)
        self.composed = String(composed)
        self.romaji = String(romaji)


def _add(mut rows: List[KanaFixture], kana: StringSlice, romaji: StringSlice):
    rows.append(KanaFixture(kana, romaji))


def kana_fixtures() -> List[KanaFixture]:
    """Return every fixed-output monograph and digraph spelling."""
    var rows = List[KanaFixture]()

    # Hiragana monographs.
    _add(rows, "ぁ", "a")
    _add(rows, "あ", "a")
    _add(rows, "ぃ", "i")
    _add(rows, "い", "i")
    _add(rows, "ぅ", "u")
    _add(rows, "う", "u")
    _add(rows, "ぇ", "e")
    _add(rows, "え", "e")
    _add(rows, "ぉ", "o")
    _add(rows, "お", "o")
    _add(rows, "か", "ka")
    _add(rows, "ゕ", "ka")
    _add(rows, "き", "ki")
    _add(rows, "く", "ku")
    _add(rows, "け", "ke")
    _add(rows, "ゖ", "ke")
    _add(rows, "こ", "ko")
    _add(rows, "さ", "sa")
    _add(rows, "し", "shi")
    _add(rows, "す", "su")
    _add(rows, "せ", "se")
    _add(rows, "そ", "so")
    _add(rows, "た", "ta")
    _add(rows, "ち", "chi")
    _add(rows, "っ", "っ")
    _add(rows, "つ", "tsu")
    _add(rows, "て", "te")
    _add(rows, "と", "to")
    _add(rows, "な", "na")
    _add(rows, "に", "ni")
    _add(rows, "ぬ", "nu")
    _add(rows, "ね", "ne")
    _add(rows, "の", "no")
    _add(rows, "は", "ha")
    _add(rows, "ひ", "hi")
    _add(rows, "ふ", "fu")
    _add(rows, "へ", "he")
    _add(rows, "ほ", "ho")
    _add(rows, "ま", "ma")
    _add(rows, "み", "mi")
    _add(rows, "む", "mu")
    _add(rows, "め", "me")
    _add(rows, "も", "mo")
    _add(rows, "ゃ", "ya")
    _add(rows, "や", "ya")
    _add(rows, "ゅ", "yu")
    _add(rows, "ゆ", "yu")
    _add(rows, "ょ", "yo")
    _add(rows, "よ", "yo")
    _add(rows, "ら", "ra")
    _add(rows, "り", "ri")
    _add(rows, "る", "ru")
    _add(rows, "れ", "re")
    _add(rows, "ろ", "ro")
    _add(rows, "ゎ", "wa")
    _add(rows, "わ", "wa")
    _add(rows, "ゐ", "wi")
    _add(rows, "ゑ", "we")
    _add(rows, "を", "o")
    _add(rows, "ん", "n")
    _add(rows, "が", "ga")
    _add(rows, "ぎ", "gi")
    _add(rows, "ぐ", "gu")
    _add(rows, "げ", "ge")
    _add(rows, "ご", "go")
    _add(rows, "ざ", "za")
    _add(rows, "じ", "ji")
    _add(rows, "ず", "zu")
    _add(rows, "ぜ", "ze")
    _add(rows, "ぞ", "zo")
    _add(rows, "だ", "da")
    _add(rows, "ぢ", "ji")
    _add(rows, "づ", "zu")
    _add(rows, "で", "de")
    _add(rows, "ど", "do")
    _add(rows, "ば", "ba")
    _add(rows, "び", "bi")
    _add(rows, "ぶ", "bu")
    _add(rows, "べ", "be")
    _add(rows, "ぼ", "bo")
    _add(rows, "ぱ", "pa")
    _add(rows, "ぴ", "pi")
    _add(rows, "ぷ", "pu")
    _add(rows, "ぺ", "pe")
    _add(rows, "ぽ", "po")
    _add(rows, "ゔ", "vu")

    # Katakana monographs.
    _add(rows, "ァ", "a")
    _add(rows, "ア", "a")
    _add(rows, "ィ", "i")
    _add(rows, "イ", "i")
    _add(rows, "ゥ", "u")
    _add(rows, "ウ", "u")
    _add(rows, "ェ", "e")
    _add(rows, "エ", "e")
    _add(rows, "ォ", "o")
    _add(rows, "オ", "o")
    _add(rows, "カ", "ka")
    _add(rows, "ヵ", "ka")
    _add(rows, "キ", "ki")
    _add(rows, "ク", "ku")
    _add(rows, "ケ", "ke")
    _add(rows, "ヶ", "ke")
    _add(rows, "コ", "ko")
    _add(rows, "サ", "sa")
    _add(rows, "シ", "shi")
    _add(rows, "ス", "su")
    _add(rows, "セ", "se")
    _add(rows, "ソ", "so")
    _add(rows, "タ", "ta")
    _add(rows, "チ", "chi")
    _add(rows, "ッ", "ッ")
    _add(rows, "ツ", "tsu")
    _add(rows, "テ", "te")
    _add(rows, "ト", "to")
    _add(rows, "ナ", "na")
    _add(rows, "ニ", "ni")
    _add(rows, "ヌ", "nu")
    _add(rows, "ネ", "ne")
    _add(rows, "ノ", "no")
    _add(rows, "ハ", "ha")
    _add(rows, "ヒ", "hi")
    _add(rows, "フ", "fu")
    _add(rows, "ヘ", "he")
    _add(rows, "ホ", "ho")
    _add(rows, "マ", "ma")
    _add(rows, "ミ", "mi")
    _add(rows, "ム", "mu")
    _add(rows, "メ", "me")
    _add(rows, "モ", "mo")
    _add(rows, "ャ", "ya")
    _add(rows, "ヤ", "ya")
    _add(rows, "ュ", "yu")
    _add(rows, "ユ", "yu")
    _add(rows, "ョ", "yo")
    _add(rows, "ヨ", "yo")
    _add(rows, "ラ", "ra")
    _add(rows, "リ", "ri")
    _add(rows, "ル", "ru")
    _add(rows, "レ", "re")
    _add(rows, "ロ", "ro")
    _add(rows, "ヮ", "wa")
    _add(rows, "ワ", "wa")
    _add(rows, "ヰ", "wi")
    _add(rows, "ヱ", "we")
    _add(rows, "ヲ", "o")
    _add(rows, "ン", "n")
    _add(rows, "ガ", "ga")
    _add(rows, "ギ", "gi")
    _add(rows, "グ", "gu")
    _add(rows, "ゲ", "ge")
    _add(rows, "ゴ", "go")
    _add(rows, "ザ", "za")
    _add(rows, "ジ", "ji")
    _add(rows, "ズ", "zu")
    _add(rows, "ゼ", "ze")
    _add(rows, "ゾ", "zo")
    _add(rows, "ダ", "da")
    _add(rows, "ヂ", "ji")
    _add(rows, "ヅ", "zu")
    _add(rows, "デ", "de")
    _add(rows, "ド", "do")
    _add(rows, "バ", "ba")
    _add(rows, "ビ", "bi")
    _add(rows, "ブ", "bu")
    _add(rows, "ベ", "be")
    _add(rows, "ボ", "bo")
    _add(rows, "パ", "pa")
    _add(rows, "ピ", "pi")
    _add(rows, "プ", "pu")
    _add(rows, "ペ", "pe")
    _add(rows, "ポ", "po")
    _add(rows, "ヴ", "vu")

    # Contextual units in their standalone, pass-through contexts.
    _add(rows, "ー", "ー")

    # Canonically decomposed voiced and semi-voiced monographs.
    _add(rows, "か\u3099", "ga")
    _add(rows, "き\u3099", "gi")
    _add(rows, "く\u3099", "gu")
    _add(rows, "け\u3099", "ge")
    _add(rows, "こ\u3099", "go")
    _add(rows, "さ\u3099", "za")
    _add(rows, "し\u3099", "ji")
    _add(rows, "す\u3099", "zu")
    _add(rows, "せ\u3099", "ze")
    _add(rows, "そ\u3099", "zo")
    _add(rows, "た\u3099", "da")
    _add(rows, "ち\u3099", "ji")
    _add(rows, "つ\u3099", "zu")
    _add(rows, "て\u3099", "de")
    _add(rows, "と\u3099", "do")
    _add(rows, "は\u3099", "ba")
    _add(rows, "ひ\u3099", "bi")
    _add(rows, "ふ\u3099", "bu")
    _add(rows, "へ\u3099", "be")
    _add(rows, "ほ\u3099", "bo")
    _add(rows, "は\u309A", "pa")
    _add(rows, "ひ\u309A", "pi")
    _add(rows, "ふ\u309A", "pu")
    _add(rows, "へ\u309A", "pe")
    _add(rows, "ほ\u309A", "po")
    _add(rows, "う\u3099", "vu")
    _add(rows, "カ\u3099", "ga")
    _add(rows, "キ\u3099", "gi")
    _add(rows, "ク\u3099", "gu")
    _add(rows, "ケ\u3099", "ge")
    _add(rows, "コ\u3099", "go")
    _add(rows, "サ\u3099", "za")
    _add(rows, "シ\u3099", "ji")
    _add(rows, "ス\u3099", "zu")
    _add(rows, "セ\u3099", "ze")
    _add(rows, "ソ\u3099", "zo")
    _add(rows, "タ\u3099", "da")
    _add(rows, "チ\u3099", "ji")
    _add(rows, "ツ\u3099", "zu")
    _add(rows, "テ\u3099", "de")
    _add(rows, "ト\u3099", "do")
    _add(rows, "ハ\u3099", "ba")
    _add(rows, "ヒ\u3099", "bi")
    _add(rows, "フ\u3099", "bu")
    _add(rows, "ヘ\u3099", "be")
    _add(rows, "ホ\u3099", "bo")
    _add(rows, "ハ\u309A", "pa")
    _add(rows, "ヒ\u309A", "pi")
    _add(rows, "フ\u309A", "pu")
    _add(rows, "ヘ\u309A", "pe")
    _add(rows, "ホ\u309A", "po")
    _add(rows, "ウ\u3099", "vu")

    # Hiragana yoon.
    _add(rows, "きゃ", "kya")
    _add(rows, "きゅ", "kyu")
    _add(rows, "きょ", "kyo")
    _add(rows, "しゃ", "sha")
    _add(rows, "しゅ", "shu")
    _add(rows, "しょ", "sho")
    _add(rows, "ちゃ", "cha")
    _add(rows, "ちゅ", "chu")
    _add(rows, "ちょ", "cho")
    _add(rows, "にゃ", "nya")
    _add(rows, "にゅ", "nyu")
    _add(rows, "にょ", "nyo")
    _add(rows, "ひゃ", "hya")
    _add(rows, "ひゅ", "hyu")
    _add(rows, "ひょ", "hyo")
    _add(rows, "みゃ", "mya")
    _add(rows, "みゅ", "myu")
    _add(rows, "みょ", "myo")
    _add(rows, "りゃ", "rya")
    _add(rows, "りゅ", "ryu")
    _add(rows, "りょ", "ryo")
    _add(rows, "ぎゃ", "gya")
    _add(rows, "ぎゅ", "gyu")
    _add(rows, "ぎょ", "gyo")
    _add(rows, "じゃ", "ja")
    _add(rows, "じゅ", "ju")
    _add(rows, "じょ", "jo")
    _add(rows, "ぢゃ", "ja")
    _add(rows, "ぢゅ", "ju")
    _add(rows, "ぢょ", "jo")
    _add(rows, "びゃ", "bya")
    _add(rows, "びゅ", "byu")
    _add(rows, "びょ", "byo")
    _add(rows, "ぴゃ", "pya")
    _add(rows, "ぴゅ", "pyu")
    _add(rows, "ぴょ", "pyo")

    # Katakana yoon.
    _add(rows, "キャ", "kya")
    _add(rows, "キュ", "kyu")
    _add(rows, "キョ", "kyo")
    _add(rows, "シャ", "sha")
    _add(rows, "シュ", "shu")
    _add(rows, "ショ", "sho")
    _add(rows, "チャ", "cha")
    _add(rows, "チュ", "chu")
    _add(rows, "チョ", "cho")
    _add(rows, "ニャ", "nya")
    _add(rows, "ニュ", "nyu")
    _add(rows, "ニョ", "nyo")
    _add(rows, "ヒャ", "hya")
    _add(rows, "ヒュ", "hyu")
    _add(rows, "ヒョ", "hyo")
    _add(rows, "ミャ", "mya")
    _add(rows, "ミュ", "myu")
    _add(rows, "ミョ", "myo")
    _add(rows, "リャ", "rya")
    _add(rows, "リュ", "ryu")
    _add(rows, "リョ", "ryo")
    _add(rows, "ギャ", "gya")
    _add(rows, "ギュ", "gyu")
    _add(rows, "ギョ", "gyo")
    _add(rows, "ジャ", "ja")
    _add(rows, "ジュ", "ju")
    _add(rows, "ジョ", "jo")
    _add(rows, "ヂャ", "ja")
    _add(rows, "ヂュ", "ju")
    _add(rows, "ヂョ", "jo")
    _add(rows, "ビャ", "bya")
    _add(rows, "ビュ", "byu")
    _add(rows, "ビョ", "byo")
    _add(rows, "ピャ", "pya")
    _add(rows, "ピュ", "pyu")
    _add(rows, "ピョ", "pyo")

    # Canonically decomposed voiced and semi-voiced yoon.
    _add(rows, "き\u3099ゃ", "gya")
    _add(rows, "き\u3099ゅ", "gyu")
    _add(rows, "き\u3099ょ", "gyo")
    _add(rows, "し\u3099ゃ", "ja")
    _add(rows, "し\u3099ゅ", "ju")
    _add(rows, "し\u3099ょ", "jo")
    _add(rows, "ち\u3099ゃ", "ja")
    _add(rows, "ち\u3099ゅ", "ju")
    _add(rows, "ち\u3099ょ", "jo")
    _add(rows, "ひ\u3099ゃ", "bya")
    _add(rows, "ひ\u3099ゅ", "byu")
    _add(rows, "ひ\u3099ょ", "byo")
    _add(rows, "ひ\u309Aゃ", "pya")
    _add(rows, "ひ\u309Aゅ", "pyu")
    _add(rows, "ひ\u309Aょ", "pyo")
    _add(rows, "キ\u3099ャ", "gya")
    _add(rows, "キ\u3099ュ", "gyu")
    _add(rows, "キ\u3099ョ", "gyo")
    _add(rows, "シ\u3099ャ", "ja")
    _add(rows, "シ\u3099ュ", "ju")
    _add(rows, "シ\u3099ョ", "jo")
    _add(rows, "チ\u3099ャ", "ja")
    _add(rows, "チ\u3099ュ", "ju")
    _add(rows, "チ\u3099ョ", "jo")
    _add(rows, "ヒ\u3099ャ", "bya")
    _add(rows, "ヒ\u3099ュ", "byu")
    _add(rows, "ヒ\u3099ョ", "byo")
    _add(rows, "ヒ\u309Aャ", "pya")
    _add(rows, "ヒ\u309Aュ", "pyu")
    _add(rows, "ヒ\u309Aョ", "pyo")

    # Hiragana extended digraphs.
    _add(rows, "ふぁ", "fa")
    _add(rows, "ふぃ", "fi")
    _add(rows, "ふぇ", "fe")
    _add(rows, "ふぉ", "fo")
    _add(rows, "ふゅ", "fyu")
    _add(rows, "ゔぁ", "va")
    _add(rows, "ゔぃ", "vi")
    _add(rows, "ゔぇ", "ve")
    _add(rows, "ゔぉ", "vo")
    _add(rows, "ゔゅ", "vyu")
    _add(rows, "てぃ", "ti")
    _add(rows, "でぃ", "di")
    _add(rows, "とぅ", "tu")
    _add(rows, "どぅ", "du")
    _add(rows, "てゅ", "tyu")
    _add(rows, "でゅ", "dyu")
    _add(rows, "うぃ", "wi")
    _add(rows, "うぇ", "we")
    _add(rows, "うぉ", "wo")
    _add(rows, "しぇ", "she")
    _add(rows, "じぇ", "je")
    _add(rows, "ちぇ", "che")
    _add(rows, "つぁ", "tsa")
    _add(rows, "つぃ", "tsi")
    _add(rows, "つぇ", "tse")
    _add(rows, "つぉ", "tso")
    _add(rows, "いぇ", "ye")

    # Katakana extended digraphs.
    _add(rows, "ファ", "fa")
    _add(rows, "フィ", "fi")
    _add(rows, "フェ", "fe")
    _add(rows, "フォ", "fo")
    _add(rows, "フュ", "fyu")
    _add(rows, "ヴァ", "va")
    _add(rows, "ヴィ", "vi")
    _add(rows, "ヴェ", "ve")
    _add(rows, "ヴォ", "vo")
    _add(rows, "ヴュ", "vyu")
    _add(rows, "ティ", "ti")
    _add(rows, "ディ", "di")
    _add(rows, "トゥ", "tu")
    _add(rows, "ドゥ", "du")
    _add(rows, "テュ", "tyu")
    _add(rows, "デュ", "dyu")
    _add(rows, "ウィ", "wi")
    _add(rows, "ウェ", "we")
    _add(rows, "ウォ", "wo")
    _add(rows, "シェ", "she")
    _add(rows, "ジェ", "je")
    _add(rows, "チェ", "che")
    _add(rows, "ツァ", "tsa")
    _add(rows, "ツィ", "tsi")
    _add(rows, "ツェ", "tse")
    _add(rows, "ツォ", "tso")
    _add(rows, "イェ", "ye")

    # Canonically decomposed voiced extended digraphs.
    _add(rows, "う\u3099ぁ", "va")
    _add(rows, "う\u3099ぃ", "vi")
    _add(rows, "う\u3099ぇ", "ve")
    _add(rows, "う\u3099ぉ", "vo")
    _add(rows, "う\u3099ゅ", "vyu")
    _add(rows, "て\u3099ぃ", "di")
    _add(rows, "と\u3099ぅ", "du")
    _add(rows, "て\u3099ゅ", "dyu")
    _add(rows, "し\u3099ぇ", "je")
    _add(rows, "ウ\u3099ァ", "va")
    _add(rows, "ウ\u3099ィ", "vi")
    _add(rows, "ウ\u3099ェ", "ve")
    _add(rows, "ウ\u3099ォ", "vo")
    _add(rows, "ウ\u3099ュ", "vyu")
    _add(rows, "テ\u3099ィ", "di")
    _add(rows, "ト\u3099ゥ", "du")
    _add(rows, "テ\u3099ュ", "dyu")
    _add(rows, "シ\u3099ェ", "je")

    return rows^


def kana_voicing_fixtures() -> List[KanaVoicingFixture]:
    """Return the complete standard kana base/mark composition table."""
    var rows = List[KanaVoicingFixture]()
    rows.append(KanaVoicingFixture("か", "\u3099", "が", "ga"))
    rows.append(KanaVoicingFixture("き", "\u3099", "ぎ", "gi"))
    rows.append(KanaVoicingFixture("く", "\u3099", "ぐ", "gu"))
    rows.append(KanaVoicingFixture("け", "\u3099", "げ", "ge"))
    rows.append(KanaVoicingFixture("こ", "\u3099", "ご", "go"))
    rows.append(KanaVoicingFixture("さ", "\u3099", "ざ", "za"))
    rows.append(KanaVoicingFixture("し", "\u3099", "じ", "ji"))
    rows.append(KanaVoicingFixture("す", "\u3099", "ず", "zu"))
    rows.append(KanaVoicingFixture("せ", "\u3099", "ぜ", "ze"))
    rows.append(KanaVoicingFixture("そ", "\u3099", "ぞ", "zo"))
    rows.append(KanaVoicingFixture("た", "\u3099", "だ", "da"))
    rows.append(KanaVoicingFixture("ち", "\u3099", "ぢ", "ji"))
    rows.append(KanaVoicingFixture("つ", "\u3099", "づ", "zu"))
    rows.append(KanaVoicingFixture("て", "\u3099", "で", "de"))
    rows.append(KanaVoicingFixture("と", "\u3099", "ど", "do"))
    rows.append(KanaVoicingFixture("は", "\u3099", "ば", "ba"))
    rows.append(KanaVoicingFixture("ひ", "\u3099", "び", "bi"))
    rows.append(KanaVoicingFixture("ふ", "\u3099", "ぶ", "bu"))
    rows.append(KanaVoicingFixture("へ", "\u3099", "べ", "be"))
    rows.append(KanaVoicingFixture("ほ", "\u3099", "ぼ", "bo"))
    rows.append(KanaVoicingFixture("は", "\u309A", "ぱ", "pa"))
    rows.append(KanaVoicingFixture("ひ", "\u309A", "ぴ", "pi"))
    rows.append(KanaVoicingFixture("ふ", "\u309A", "ぷ", "pu"))
    rows.append(KanaVoicingFixture("へ", "\u309A", "ぺ", "pe"))
    rows.append(KanaVoicingFixture("ほ", "\u309A", "ぽ", "po"))
    rows.append(KanaVoicingFixture("う", "\u3099", "ゔ", "vu"))
    rows.append(KanaVoicingFixture("カ", "\u3099", "ガ", "ga"))
    rows.append(KanaVoicingFixture("キ", "\u3099", "ギ", "gi"))
    rows.append(KanaVoicingFixture("ク", "\u3099", "グ", "gu"))
    rows.append(KanaVoicingFixture("ケ", "\u3099", "ゲ", "ge"))
    rows.append(KanaVoicingFixture("コ", "\u3099", "ゴ", "go"))
    rows.append(KanaVoicingFixture("サ", "\u3099", "ザ", "za"))
    rows.append(KanaVoicingFixture("シ", "\u3099", "ジ", "ji"))
    rows.append(KanaVoicingFixture("ス", "\u3099", "ズ", "zu"))
    rows.append(KanaVoicingFixture("セ", "\u3099", "ゼ", "ze"))
    rows.append(KanaVoicingFixture("ソ", "\u3099", "ゾ", "zo"))
    rows.append(KanaVoicingFixture("タ", "\u3099", "ダ", "da"))
    rows.append(KanaVoicingFixture("チ", "\u3099", "ヂ", "ji"))
    rows.append(KanaVoicingFixture("ツ", "\u3099", "ヅ", "zu"))
    rows.append(KanaVoicingFixture("テ", "\u3099", "デ", "de"))
    rows.append(KanaVoicingFixture("ト", "\u3099", "ド", "do"))
    rows.append(KanaVoicingFixture("ハ", "\u3099", "バ", "ba"))
    rows.append(KanaVoicingFixture("ヒ", "\u3099", "ビ", "bi"))
    rows.append(KanaVoicingFixture("フ", "\u3099", "ブ", "bu"))
    rows.append(KanaVoicingFixture("ヘ", "\u3099", "ベ", "be"))
    rows.append(KanaVoicingFixture("ホ", "\u3099", "ボ", "bo"))
    rows.append(KanaVoicingFixture("ハ", "\u309A", "パ", "pa"))
    rows.append(KanaVoicingFixture("ヒ", "\u309A", "ピ", "pi"))
    rows.append(KanaVoicingFixture("フ", "\u309A", "プ", "pu"))
    rows.append(KanaVoicingFixture("ヘ", "\u309A", "ペ", "pe"))
    rows.append(KanaVoicingFixture("ホ", "\u309A", "ポ", "po"))
    rows.append(KanaVoicingFixture("ウ", "\u3099", "ヴ", "vu"))
    return rows^
