context:
  version: "0.1.0"

package:
  name: mojo-yomi
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - mojo precompile src/yomi -o ${{ PREFIX }}/lib/mojo/yomi.mojoc

requirements:
  build:
    - mojo-compiler ==1.0.0
  host:
    - mojo-compiler ==1.0.0
  run:
    - mojo-compiler ==1.0.0

tests:
  - script:
      - mojo run test_package.mojo
    files:
      recipe:
        - test_package.mojo

about:
  homepage: https://github.com/Ameyanagi/yomi
  repository: https://github.com/Ameyanagi/yomi
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - LICENSES/pinyin-data-MIT.txt
  summary: CJK phonetic representations and readings for Mojo.

extra:
  maintainers:
    - Ameyanagi
